### ISSUE TITLE
App freezes after suspend/resume

### ISSUE THREAD

**Issue by bluppfisk** [nilgradisnik/coinprice-indicator#10]
When suspending and resuming the computer, the app is unresponsive. Prices stay and no functionality (not even quit) works.

**Comment by sebster** [comment]
I consistently have this issue... I suspend twice a day, and it fails almost every time. Seems it needs to be suspended for a while though before it fails (just closing the lid and opening 30 seconds later does not cause the issue). I don't know if there is an error log somewhere, I will try redirecting stdin and stderr to a log file and see if I get any messages.

**Comment by bluppfisk** [comment]
Hm you're right. I've just been able to be reproduce it again. I'll reopen and look into what can be done when the app receives the suspend or resume signals if I have some time later this week.

If you could get some logs, that would be most helpful!

**Comment by bluppfisk** [comment]
Hm you're right. I've just been able to be reproduce it again. I'll reopen and look into what can be done when the app receives the suspend or resume signals if I have some time later this week.

If you could get some logs, that would be most helpful!

**Comment by bluppfisk** [comment]
@sebster 

I just had my laptop closed for 3 hours and the app resumed normally after reopening the lid.
Are you running it backgrounded (i.e. with the unix & operator) or foregrounded?

**Comment by sebster** [comment]
I'm running it in the background.

**Comment by bluppfisk** [comment]
@sebster  Thanks. I'll go sleuthing around. Let me know if you have any logs

**Comment by sebster** [comment]
The redirect of stdout and stderr unfortunately hasn't given me any log lines even when it fails...

**Comment by bluppfisk** [comment]
Hm yes, same here.
How often are you able to reproduce this? And is your computer hibernating or just sleeping? I'm at a loss as to what might cause it.

**Comment by sebster** [comment]
It happens a lot during the week when I take my computer to work and back and close the lid. It's just sleeping then.

**Comment by bluppfisk** [comment]
I've a bit of new information. I just had it seemingly stall on me while I was using the computer. Maybe it was just a network error for a while, maybe it was stalling. At any rate, after foregrounding and re-backgrounding the process, it continued. @sebster can you confirm that this works the next time it happens to you?

**Comment by sebster** [comment]
I'll check this out tomorrow. Meanwhile I discovered that python wasn't logging the redirected logging output because it buffers stdout. I've turned off the buffering with the -u option, so if I get some relevant logging I'll post it here.

**Comment by bluppfisk** [comment]
@sebster any news? If it still happens, also try pulling the new set-up. Although I'll have to refactor the code a bit after this.

**Comment by sebster** [comment]
Still had the old code, but these were the logs. Note that it actually was working after 18:02 until 18:22 but then I closed my laptop and was broken after that. No more logs were received... I'll upgrade and restart and see what happens next time.

2017-09-05 18:01:57 HTTPSConnectionPool(host='api.kraken.com', port=443): Max retries exceeded with url: /0/public/Ticker?pair=BCHEUR (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc31327e3c8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
2017-09-05 18:01:57 Warning: maximum error count reached [5]. Cooling down (60s refresh)
2017-09-05 18:02:57 All ok. Restoring normal refresh frequency.
2017-09-05 18:02:57 All ok. Restoring normal refresh frequency.
2017-09-05 18:02:58 All ok. Restoring normal refresh frequency.

**Comment by sebster** [comment]
I haven't seen the issue in a while, so for me this issue can be closed.

**Comment by bluppfisk** [comment]
Closing for now, code needs a serious overhaul though that will probably help disappear this issue.

**Comment by bluppfisk** [comment]
@sebster just in case you had the issue again -- I think my recent code changes should fix most of that. It now also refreshes the exchanges after resuming from sleep.
