### ISSUE TITLE
Nice Project! Could you add BitYep Price?

### ISSUE THREAD

**Issue by algorithmcode** [nilgradisnik/coinprice-indicator#8]
Price API:
https://bityep.com/api/1/ticker

Thanks!

**Comment by bluppfisk** [comment]
I can add this later this week

**Comment by bluppfisk** [comment]
BitYep support added in my newest commit (in the fork https://github.com/bluppfisk/coinprice-indicator). You can download that one or wait a bit until @nilgradisnik pulls this commit into the master branch.

Had to change quite a few things in order to achieve this. One is the use of an standardised format to refer to the asset pair: XXBCZXBT (X = from, Z = to; XBC = Bitcoin Cash, XBT = Bitcoin) - even if the exchange itself reports different pairs (e.g. Kraken calls this BCHEUR but uses iso-compatible elsewhere, e.g. XXBTZEUR; BitYep simply uses 0 and 1 for its two asset pairs).

That makes running from the commandline somewhat more consistent and predictable, and you don't have to know about the API.

**Comment by bluppfisk** [comment]
PS, run `make install` again to ensure that the settings file also includes the bityep setting. Somehow I don't really like this, I'd like to rewrite the whole settings thing.

**Comment by bluppfisk** [comment]
Added
